# Generated by Django 5.2 on 2025-04-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hall_camera_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='source',
            new_name='stream',
        ),
    ]
