# Generated by Django 5.2 on 2025-05-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_source_camera_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='video_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
