# Generated by Django 5.2.3 on 2025-06-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_camera_is_live_camera_video_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('academic_id', models.CharField(max_length=20)),
                ('hall_name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
