# Generated by Django 5.2.3 on 2025-06-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cheatingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='floor',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
